/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWeeklyRouteImport } from './routes/_app/weekly'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppBasketRouteImport } from './routes/_app/basket'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAccountRouteImport } from './routes/_app/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeeklyRoute = AppWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppBasketRoute = AppBasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/basket': typeof AppBasketRoute
  '/savings': typeof AppSavingsRoute
  '/weekly': typeof AppWeeklyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/basket': typeof AppBasketRoute
  '/savings': typeof AppSavingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/basket': typeof AppBasketRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/weekly': typeof AppWeeklyRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/account' | '/admin' | '/basket' | '/savings' | '/weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/login' | '/account' | '/admin' | '/basket' | '/savings' | '/weekly' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/basket'
    | '/_app/savings'
    | '/_app/weekly'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weekly': {
      id: '/_app/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AppWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/basket': {
      id: '/_app/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof AppBasketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppBasketRoute: typeof AppBasketRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppWeeklyRoute: typeof AppWeeklyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppBasketRoute: AppBasketRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppWeeklyRoute: AppWeeklyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
