/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWeeklyRouteImport } from './routes/_app/weekly'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppBasketRouteImport } from './routes/_app/basket'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppDealDealIdRouteImport } from './routes/_app/deal.$dealId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeeklyRoute = AppWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBasketRoute = AppBasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppDealDealIdRoute = AppDealDealIdRouteImport.update({
  id: '/deal/$dealId',
  path: '/deal/$dealId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/basket': typeof AppBasketRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/savings': typeof AppSavingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/deal/$dealId': typeof AppDealDealIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/basket': typeof AppBasketRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/savings': typeof AppSavingsRoute
  '/weekly': typeof AppWeeklyRoute
  '/': typeof AppIndexRoute
  '/deal/$dealId': typeof AppDealDealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/basket': typeof AppBasketRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/weekly': typeof AppWeeklyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/deal/$dealId': typeof AppDealDealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/account'
    | '/admin'
    | '/basket'
    | '/leaderboard'
    | '/savings'
    | '/weekly'
    | '/deal/$dealId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/account'
    | '/admin'
    | '/basket'
    | '/leaderboard'
    | '/savings'
    | '/weekly'
    | '/'
    | '/deal/$dealId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/basket'
    | '/_app/leaderboard'
    | '/_app/savings'
    | '/_app/weekly'
    | '/_app/'
    | '/_app/deal/$dealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weekly': {
      id: '/_app/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AppWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/basket': {
      id: '/_app/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof AppBasketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deal/$dealId': {
      id: '/_app/deal/$dealId'
      path: '/deal/$dealId'
      fullPath: '/deal/$dealId'
      preLoaderRoute: typeof AppDealDealIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppBasketRoute: typeof AppBasketRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppWeeklyRoute: typeof AppWeeklyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDealDealIdRoute: typeof AppDealDealIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppBasketRoute: AppBasketRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppWeeklyRoute: AppWeeklyRoute,
  AppIndexRoute: AppIndexRoute,
  AppDealDealIdRoute: AppDealDealIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
